#!/usr/bin/env node
/**
 * Legacy surface inventory — plan v3 unit 1's evidence step.
 *
 * Reads the **read-only** PHPRetro checkout and prints a Markdown route/action
 * map: every entry point, the permission idiom it uses, and the tables it
 * writes. It is deliberately a *static* extraction: it reports what the source
 * says and never guesses what a route does at runtime, so a row is only as
 * strong as the file it was read from.
 *
 * Usage:
 *   node scripts/legacy_surface_inventory.mjs [CHECKOUT] > docs/legacy-surface-inventory.md
 *
 * Default CHECKOUT is `../legacy/phpretro-pdo`, the sibling path `compose.yaml`
 * mounts. Nothing is written back into the checkout and nothing is executed from
 * it: the reference must stay read-only (plan rule 8).
 *
 * What it extracts, and why each one:
 *
 *   - `$page['rank'] = …` and `includes/hksession.php` — how a housekeeping page
 *     states its own permission. A page with no rank is either public or gated
 *     some other way, and both are worth seeing rather than assuming.
 *   - `$page['allow_guests']` and `includes/session.php` — whether an anonymous
 *     visitor reaches the page, which is what the port's guard has to match.
 *   - `INSERT`/`UPDATE`/`DELETE`/`REPLACE` targets — the table effects a port
 *     must reproduce through named service methods. Reads are counted but not
 *     listed: every page reads, and the write set is what ownership turns on.
 *   - `.htaccess` `RewriteRule`s — the URL shapes the legacy site actually
 *     served, which is how a habblet is reached and what the React router has to
 *     keep alive.
 */

import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

const root = process.argv[2] ?? '../legacy/phpretro-pdo';

/** Every `.php` file under a directory, one level deep, sorted by name. */
function phpFiles(dir) {
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return [];
  }
  return entries
    .filter((name) => name.endsWith('.php'))
    .sort()
    .map((name) => join(dir, name))
    .filter((path) => statSync(path).isFile());
}

const WRITE_VERBS = /\b(INSERT|REPLACE)\s+(?:IGNORE\s+)?INTO\s+`?([a-zA-Z0-9_]+)`?|\bUPDATE\s+`?([a-zA-Z0-9_]+)`?|\bDELETE\s+FROM\s+`?([a-zA-Z0-9_]+)`?/gi;
const READ_TABLE = /\bFROM\s+`?([a-zA-Z0-9_]+)`?/gi;

/** Tables a file writes to, in first-seen order. */
function writeTargets(source) {
  const found = [];
  for (const match of source.matchAll(WRITE_VERBS)) {
    const table = match[2] ?? match[3] ?? match[4];
    if (table && !found.includes(table)) found.push(table);
  }
  return found;
}

function readTargets(source) {
  const found = new Set();
  for (const match of source.matchAll(READ_TABLE)) found.add(match[1]);
  return [...found];
}

/** The first `$page['rank'] = …;` assignment, verbatim. */
function rank(source) {
  const match = /\$page\['rank'\]\s*=\s*([^;]+);/.exec(source);
  return match ? match[1].trim() : '';
}

function row(path, source) {
  const writes = writeTargets(source);
  const reads = readTargets(source);
  const staffSession = source.includes('hksession.php');
  const userSession = /require(_once)?\s*\(?[^;]*session\.php/.test(source);
  const guests = /\$page\['allow_guests'\]\s*=\s*(true|1)/.test(source);
  const rankExpr = rank(source);
  return {
    file: relative(root, path).replace(/\\/g, '/'),
    rank: rankExpr || (staffSession ? '(hksession, no $page[rank])' : ''),
    gate: staffSession ? 'staff' : userSession ? 'signed-in' : guests ? 'guests allowed' : '',
    writes: writes.length ? writes.join(', ') : '',
    reads: reads.length,
  };
}

function table(rows, columns) {
  const head = `| ${columns.join(' | ')} |\n| ${columns.map(() => '---').join(' | ')} |`;
  const body = rows
    .map((r) => `| ${columns.map((c) => String(r[c] ?? '')).join(' | ')} |`)
    .join('\n');
  return `${head}\n${body}`;
}

function section(title, dir, columns) {
  const files = phpFiles(join(root, dir));
  if (files.length === 0) return `### ${title}\n\n_(no files found at \`${dir}\`)_\n`;
  const rows = files.map((path) => row(path, readFileSync(path, 'utf8')));
  const writers = rows.filter((r) => r.writes).length;
  return (
    `### ${title}\n\n` +
    `\`${dir}\` holds **${rows.length}** entry points; **${writers}** of them write to a table.\n\n` +
    table(rows, columns) +
    '\n'
  );
}

console.log(`# Legacy surface inventory (generated)

Generated by \`scripts/legacy_surface_inventory.mjs\` from the read-only PHPRetro
checkout at \`${root}\`. **Do not edit by hand** — re-run the script after the
checkout moves, and keep the judgement (ported / gap / gate) in
\`docs/phase1-parity-inventory.md\` and \`docs/modular-cms-contracts.md\`, which is
where a reviewer should look.

A blank \`rank\` cell means the file does not declare one; it does not mean the
page is public. A blank \`writes\` cell means no write verb appears in the file,
not that the route is read-only at runtime.
`);

console.log(section('Top-level entry points', '.', ['file', 'gate', 'rank', 'writes', 'reads']));
console.log(section('Habblet actions', 'habblet', ['file', 'gate', 'rank', 'writes', 'reads']));
console.log(section('Housekeeping pages', 'housekeeping', ['file', 'gate', 'rank', 'writes', 'reads']));
console.log(section('XML endpoints', 'xml', ['file', 'gate', 'rank', 'writes', 'reads']));

// ---- URL shapes the legacy front controller served -------------------------
try {
  const htaccess = readFileSync(join(root, '.htaccess'), 'utf8');
  const rules = htaccess
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.startsWith('RewriteRule'))
    .map((line) => {
      const match = /^RewriteRule\s+(\S+)\s+(\S+)/.exec(line);
      return match ? { pattern: match[1], target: match[2] } : null;
    })
    .filter(Boolean);
  console.log(`### URL shapes (\`.htaccess\`)\n`);
  console.log(`**${rules.length}** rewrite rules, which are the URLs the legacy site served.\n`);
  console.log(table(rules, ['pattern', 'target']) + '\n');
} catch {
  console.log('### URL shapes\n\n_(no `.htaccess` in the checkout)_\n');
}
